/*
 *
 * Settings constants
 *
 */

export const DEFAULT_ACTION = "app/Settings/DEFAULT_ACTION";

export const GENERATE_KEY_REQUEST = "app/Settings/GENERATE_KEY_REQUEST";
export const GENERATE_KEY_SUCCESS = "app/Settings/GENERATE_KEY_SUCCESS";
export const GENERATE_KEY_FAILURE = "app/Settings/GENERATE_KEY_FAILURE";

export const SECRET_KEY_REQUEST = "app/Settings/SECRET_KEY_REQUEST";
export const SECRET_KEY_SUCCESS = "app/Settings/SECRET_KEY_SUCCESS";
export const SECRET_KEY_FAILURE = "app/Settings/SECRET_KEY_FAILURE";

export const SECRET_STATUS_REQUEST = "app/Settings/SECRET_STATUS_REQUEST";
export const SECRET_STATUS_SUCCESS = "app/Settings/SECRET_STATUS_SUCCESS";
export const SECRET_STATUS_FAILURE = "app/Settings/SECRET_STATUS_FAILURE";

export const ACCOUNT_DETAILS_REQUEST = "app/Settings/ACCOUNT_DETAILS_REQUEST";
export const ACCOUNT_DETAILS_SUCCESS = "app/Settings/ACCOUNT_DETAILS_SUCCESS";
export const ACCOUNT_DETAILS_FAILURE = "app/Settings/ACCOUNT_DETAILS_FAILURE";

export const GET_PIPELINE_CONFIG_REQUEST = "app/Settings/GET_PIPELINE_CONFIG_REQUEST";
export const GET_PIPELINE_CONFIG_SUCCESS = "app/Settings/GET_PIPELINE_CONFIG_SUCCESS";
export const GET_PIPELINE_CONFIG_FAILURE = "app/Settings/GET_PIPELINE_CONFIG_FAILURE";

export const DELETE_SECRET_KEY = "app/Settings/DELETE_SECRET_KEY";
export const DELETE_SECRET_KEY_SUCCESS = "app/Settings/DELETE_SECRET_KEY_SUCCESS";
export const DELETE_SECRET_KEY_FAILURE = "app/Settings/DELETE_SECRET_KEY_FAILURE";

export const SUBMIT_CONFIG_DETAILS = "app/Settings/SUBMIT_CONFIG_DETAILS";
export const SUBMIT_CONFIG_DETAILS_SUCCESS = "app/Settings/SUBMIT_CONFIG_DETAILS_SUCCESS";
export const SUBMIT_CONFIG_DETAILS_FAILURE = "app/Settings/SUBMIT_CONFIG_DETAILS_FAILURE";

export const LICENSE_KEY_DETAILS = "app/Settings/LICENSE_KEY_DETAILS";
export const LICENSE_KEY_DETAILS_SUCCESS = "app/Settings/LICENSE_KEY_DETAILS_SUCCESS";
export const LICENSE_KEY_DETAILS_FAILURE = "app/Settings/LICENSE_KEY_DETAILS_FAILURE";

export const GET_LICENCE = "app/Settings/GET_LICENCE";
export const GET_LICENCE_SUCCESS = "app/Settings/GET_LICENCE_SUCCESS";
export const GET_LICENCE_FAILURE = "app/Settings/GET_LICENCE_FAILURE";

export const GET_SETTINGTABS = "app/Settings/GET_SETTINGTABS";
export const GET_SETTINGTABS_SUCCESS = "app/Settings/GET_SETTINGTABS_SUCCESS";
export const GET_SETTINGTABS_FAILURE = "app/Settings/GET_SETTINGTABS_FAILURE";
